import Head from "next/head";
import Image from "next/image";
import Nav from "co-mission/components/Nav";
import Main from "co-mission/components/Main";
import { accounts } from "co-mission/data/accountsdata";

export default function Home() {
    return (
        <>
            <Head>
                <title>Co-Mission</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Nav />
                <Main />
            </main>
        </>
    );
}
